-- 1. Thêm dữ liệu bảng KHOA
INSERT INTO KHOA (MAKHOA, TENKHOA, MAGV_TRUONGKHOA) VALUES ('CSC', 'Công nghệ thông tin', 'GV001');
INSERT INTO KHOA (MAKHOA, TENKHOA, MAGV_TRUONGKHOA) VALUES ('MTH', 'Toán - Tin', 'GV002');

-- 2. Thêm dữ liệu bảng MONHOC
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('ADD00031', 'Anh văn 1', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('ADD00032', 'Anh văn 2', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00003', 'Tư tưởng Hồ Chí Minh', 2, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00004', 'Pháp luật đại cương', 3, NULL, 'LL_CT');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00005', 'Kinh tế đại cương', 2, NULL, 'XH_TC');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00021', 'Thể dục 1', 2, NULL, 'GD_TC');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00022', 'Thể dục 2', 2, NULL, 'GD_TC');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00030', 'Giáo dục quốc phòng - An ninh', 4, NULL, 'GD_QP');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00101', 'Triết học Mác - Lênin', 3, NULL, 'LL_CT');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00102', 'Kinh tế chính trị Mác - Lênin', 2, NULL, 'LL_CT');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00103', 'Chủ nghĩa xã hội khoa học', 2, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('BAA00104', 'Lịch sử Đảng Cộng sản Việt Nam', 2, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC00003', 'Tin học cơ sở', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC00004', 'Nhập môn Công nghệ thông tin', 4, NULL, 'TH_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10003', 'Phương pháp lập trình hướng đối tượng', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10004', 'Cấu trúc dữ liệu và giải thuật', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10006', 'Cơ sở dữ liệu', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10007', 'Hệ điều hành', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10008', '	Mạng máy tính', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10009', 'Hệ thống máy tính', 2, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10012', 'Cơ sở lập trình', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10014', 'Tư duy tính toán', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC10121', 'Kỹ năng mềm', 3, NULL, 'CN_TD');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC13002', 'Nhập môn công nghệ phần mềm', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('CSC14003', 'Cơ sở trí tuệ nhân tạo', 4, NULL, 'CN_CS');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('GEO00002', 'Khoa học Trái đất', 2, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00005', 'Vi tích phân 1', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00006', 'Vi tích phân 2', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00007', 'Xác suất thống kê', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00008', 'Đại số tuyến tính', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00009', 'Toán rời rạc', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00010', 'Giải tích 1A', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00011', 'Vi tích phân 1A', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00013', 'Vi tích phân 2A', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00017', 'Phương trình vi phân', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00031', 'Đại số đại cương', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00034', 'Đại số tuyến tính 1A', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00042', 'Xác suất', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00043', 'Toán rời rạc 1A', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00052', 'Phương pháp tính cho CNTT', 4, NULL, 'TN_TC2');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00055', 'Cơ sở lập trình', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00057', 'Toán ứng dụng và thống kê cho Công nghệ thông tin', 4, NULL, 'TN_TC2');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00058', 'Toán học tổ hợp', 4, NULL, 'TN_BB');
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH00088', 'Thực hành đại số tuyến tính 1A', 1, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10109', 'Thực hành thống kê', 1, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10131', 'Lý thuyết thống kê', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10312', 'Cơ sở dữ liệu', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10405', 'Cấu trúc dữ liệu và Giải thuật', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10407', 'Lập trình hướng đối tượng', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10441', 'Đại số tuyến tính 2A', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10442', 'Toán rời rạc 2A', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('MTH10449', 'Quy hoạch tuyến tính', 4, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('PHY00001', 'Vật lý đại cương 1 (Cơ - Nhiệt)', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('PHY00002', 'Vật lý đại cương 2 (Điện từ - Quang)', 3, NULL, NULL);
INSERT INTO MONHOC (MAMH, TENMH, SOTC, SOTIET, MANHOM) VALUES ('PHY00005', 'Vật lý đại cương 1', 4, NULL, 'TN_TC2');

-- 3. Thêm dữ liệu bảng HOCKY_NAMHOC
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK001', 'HK1', '24-25', '2024-09-16', '2025-01-05', 'Closed');
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK002', 'HK2', '24-25', '2025-02-24', '2025-06-15', 'Closed');
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK003', 'HK3', '24-25', '2025-07-14', '2025-08-31', 'Closed');
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK004', 'HK1', '25-26', '2025-09-29', '2026-01-03', 'Closed');
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK005', 'HK2', '25-26', '2026-01-12', '2026-05-09', 'Closed');
INSERT INTO HOCKY_NAMHOC (MA_HOCKY, TEN_HOCKY, NAMHOC, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI) VALUES ('HK006', 'HK3', '25-26', '2026-05-18', '2026-09-05', 'Open');

-- 4. Thêm dữ liệu bảng KHAOSAT
INSERT INTO KHAOSAT (MAKS, TENKS, NOIDUNG, HANDON) VALUES ('KS001', 'Khảo sát đánh giá môn học HK2 (25-26)', 'Sinh viên thực hiện đánh giá chất lượng giảng dạy giảng viên các lớp học phần học kỳ 2 năm học 2025-2026.', '2026-08-15T23:59:00.000');

-- 5. Thêm dữ liệu bảng LIENHE_HETHONG
INSERT INTO LIENHE_HETHONG (MA_LIENHE, TEN_DONVI, LOAI_LIENHE, EMAIL, SDT, DIACHI, GHICHU) VALUES ('LH01', 'Giáo vụ ', 'Học vụ', 'giaovu@fit.hcmus.edu.vn', NULL, NULL, NULL);
INSERT INTO LIENHE_HETHONG (MA_LIENHE, TEN_DONVI, LOAI_LIENHE, EMAIL, SDT, DIACHI, GHICHU) VALUES ('LH02', 'Phòng Đào tạo', 'Học vụ', 'pdt_khtn@hcmus.edu.vn', NULL, NULL, NULL);
INSERT INTO LIENHE_HETHONG (MA_LIENHE, TEN_DONVI, LOAI_LIENHE, EMAIL, SDT, DIACHI, GHICHU) VALUES ('LH03', 'AmongUS', 'Hỗ trợ kĩ thuật', 'campusofficial2026@gmail.com', NULL, NULL, NULL);

-- 6. Thêm dữ liệu bảng GIANGVIEN
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV001', 'Đinh Bá Tiến', '', 'dbtien(at)fit.hcmus.edu.vn', '', 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV002', 'Võ Đức Cẩm Hải', '', 'vdchai@hcmus.edu.vn', '', 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV003', 'Tiết Gia Hồng', NULL, 'tghong@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV004', 'Nguyễn Hải Minh', NULL, 'nhminh@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV005', 'Lê Thu Thảo', NULL, 'ltthao@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV006', 'Lê Văn Luyện', NULL, 'lvluyen@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV007', 'Đặng Công Tráng', NULL, 'dctrang@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV008', 'Nguyễn Ngọc Thảo', NULL, 'nnthao@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV009', 'Nguyễn Hữu Trí Nhật', NULL, 'nhtnhat@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV010', 'Huỳnh Trúc Phương', NULL, 'htphuong@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV011', 'Trần Duy Quang', NULL, 'tdquang@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV012', 'Lê Hà Minh', NULL, 'lhminh@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV013', 'Nguyễn Vũ Huy', NULL, 'nvhuy@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV014', 'Nguyễn Thị Đông', NULL, 'ntdong@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV015', 'Nguyễn Hồng Bửu Long', NULL, 'nhblong@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV016', 'Lê Khánh Duy', NULL, 'lkduy@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV017', 'Lê Hải', NULL, 'lhai@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV018', 'Nguyễn Thanh Hải', NULL, 'nthai@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV019', 'Lê Viết Long', NULL, 'lvlong@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV020', 'Nguyễn Đăng Minh', NULL, 'ndminh@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV021', 'Đỗ Thành Quang', NULL, 'dtquang@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV022', 'Mạch Thị Khánh Trinh', NULL, 'mtktrinh@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV023', 'Vũ Thị Mỹ Hằng', NULL, 'vtmhang@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV024', 'Nguyễn Văn Vũ', NULL, 'nvvu@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV025', 'Vũ Quốc Hoàng', NULL, 'vqhoang@hcmus.edu.vn', NULL, 'CSC');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV026', 'Nguyễn Thị A', NULL, 'nta@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV027', 'Nguyễn Thị B', NULL, 'ntb@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV028', 'Nguyễn Thị C', NULL, 'ntc@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV029', 'Nguyễn Thị D', NULL, 'ntd@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV030', 'Nguyễn Thị E', NULL, 'nte@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV031', 'Nguyễn Thị F', NULL, 'ntf@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV032', 'Nguyễn Thị G', NULL, 'ntg@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV033', 'Nguyễn Thị H', NULL, 'nth@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV034', 'Nguyễn Thị I', NULL, 'nti@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV035', 'Nguyễn Thị J', NULL, 'ntj@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV036', 'Nguyễn Thị K', NULL, 'ntk@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV037', 'Nguyễn Thị L', NULL, 'ntl@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV038', 'Nguyễn Thị M', NULL, 'ntm@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV039', 'Nguyễn Thị N', NULL, 'ntn@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV040', 'Nguyễn Thị O', NULL, 'nto@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV041', 'Nguyễn Thị P', NULL, 'ntp@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV042', 'Nguyễn Thị Q', NULL, 'ntq@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV043', 'Nguyễn Thị R', NULL, 'ntr@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV044', 'Nguyễn Thị S', NULL, 'nts@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV045', 'Nguyễn Thị T', NULL, 'ntt@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV046', 'Nguyễn Thị U', NULL, 'ntu@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV047', 'Nguyễn Thị V', NULL, 'ntv@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV048', 'Nguyễn Thị W', NULL, 'ntw@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV049', 'Nguyễn Thị Y', NULL, 'nty@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV050', 'Nguyễn Thị Z', NULL, 'ntz@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV051', 'Trần Văn A', NULL, 'tva@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV052', 'Trần Văn B', NULL, 'tvb@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV053', 'Trần Văn C', NULL, 'tvc@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV054', 'Trần Văn D', NULL, 'tvd@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV055', 'Trần Văn E', NULL, 'tve@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV056', 'Trần Văn F', NULL, 'tvf@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV057', 'Trần Văn G', NULL, 'tvg@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV058', 'Trần Văn H', NULL, 'tvh@hcmus.edu.vn', NULL, 'MTH');
INSERT INTO GIANGVIEN (MAGV_GD, HOTEN, DIENTHOAI, MAIL, CHUYENMON, MAKHOA) VALUES ('GV059', 'Trần Văn I', NULL, 'tvi@hcmus.edu.vn', NULL, 'MTH');

-- 7. Thêm dữ liệu bảng NGANH
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7460101_NN', 'Nhóm ngành Toán học, Toán ứng dụng, Toán tin', 'MTH');
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7460108_NN', 'Nhóm ngành Khoa học dữ liệu, Thống kê', 'MTH');
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7480101_TT', 'Khoa học máy tính', 'CSC');
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7480107', 'Trí tuệ nhân tạo', 'CSC');
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7480201_DKD', 'Công nghệ Thông tin', 'CSC');
INSERT INTO NGANH (MANGANH, TENNGANH, MAKHOA) VALUES ('7480201_NN', 'Nhóm ngành máy tính và công nghệ thông tin', 'CSC');

-- 8. Thêm dữ liệu bảng DOT_CAPNHAT_HOSO 
INSERT INTO DOT_CAPNHAT_HOSO (MADOT, TENDOT, THOIGIAN_BATDAU, THOIGIAN_KETTHUC, TRANGTHAI_MO, MA_HOCKY) VALUES ('DOT01', 'Cập nhật thông tin sinh viên', '2026-08-01T00:00:00.000', '2026-08-03T23:59:00.000', 1, 'HK006');

-- 9. Thêm dữ liệu bảng CAUHOI_KHAOSAT 
INSERT INTO CAUHOI_KHAOSAT (MACH, MAKS, NOIDUNG_CAUHOI, LOAI_CAUHOI, THUTU) VALUES ('CH01', 'KS001', 'Đánh giá mức độ hài lòng về môn Cơ sở Trí tuệ nhân tạo', 'Trắc nghiệm', 1);
INSERT INTO CAUHOI_KHAOSAT (MACH, MAKS, NOIDUNG_CAUHOI, LOAI_CAUHOI, THUTU) VALUES ('CH02', 'KS001', 'Góp ý thêm cho nhà trường', 'Tự luận', 2);

-- 10. Thêm dữ liệu bảng ADMIN_GIAOVU
INSERT INTO ADMIN_GIAOVU (MAGV, HOTEN, EMAIL, VAITRO, MAKHOA, TRANGTHAI) VALUES ('GVU001', 'Đỗ Thành Vinh', '24127262@student.hcmus.edu.vn', 'Giáo vụ', 'CSC', 1);
INSERT INTO ADMIN_GIAOVU (MAGV, HOTEN, EMAIL, VAITRO, MAKHOA, TRANGTHAI) VALUES ('GVU002', 'Tạ Mai Như Ngọc', '24127465@student.hcmus.edu.vn', 'Giáo vụ', 'MTH', 1);
INSERT INTO ADMIN_GIAOVU (MAGV, HOTEN, EMAIL, VAITRO, MAKHOA, TRANGTHAI) VALUES ('GVU003', 'Nguyễn Thị Ngọc Trâm', '24127132@student.hcmus.edu.vn', 'Giáo vụ', 'CSC', 1);

-- 12. Thêm dữ liệu bảng CHUYENNGANH
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('CH', 'Cơ học', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('CNTT', 'Công nghệ thông tin', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('CNTTh', 'Công nghệ tri thức', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('DS', 'Đại số', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('GDTH', 'Giáo dục toán học', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('GT', 'Giải tích', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('GTS', 'Giải tích số', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('HTTT', 'Hệ thống thông tin', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('KHDL', 'Khoa học dữ liệu.', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('KHDL_TT', 'Khoa học dữ liệu', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('KHMT', 'Khoa học máy tính', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('KTPM', 'Kỹ thuật phần mềm', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('MMT', 'Mạng máy tính và Viễn thông', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('PPTTTH', 'Phương pháp toán trong tin học', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('TCDL', 'Tài chính định lượng', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('TGMT', 'Thị giác máy tính', '7480201_DKD');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('TTUD', 'Toán tin ứng dụng', '7460101_NN');
INSERT INTO CHUYENNGANH (MACN, TENCN, MANGANH) VALUES ('XSTK', 'Xác suất thống kê', '7460101_NN');

-- 12. Thêm dữ liệu bảng CHUONGTRINH_DAOTAO
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'ADD00031', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'ADD00032', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00003', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00004', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00005', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00021', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00022', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00101', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00102', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00103', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'BAA00104', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'CSC00003', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'GEO00002', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00010', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00011', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00013', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00017', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00031', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00034', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00042', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00043', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00055', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH00088', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10109', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10131', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10312', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10405', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10407', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10441', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10442', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'MTH10449', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'PHY00001', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7460101_NN', 'PHY00002', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00004', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00005', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00021', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00022', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00030 ', 4, 0, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00101', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'BAA00102', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC00004', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10003', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10004', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10006', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10007', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10008', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10009', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10012', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10014', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC10121', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC13002', 6, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'CSC14003', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00005', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00006', 4, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00007', 5, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00008', 3, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00009', 1, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00052', 6, 1, 'Tự chọn');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00057', 6, 1, 'Tự chọn');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'MTH00058', 2, 1, 'Bắt buộc');
INSERT INTO CHUONGTRINH_DAOTAO (MANGANH, MAMH, HOCKY_KIENGHI, TICHCHOTOTNGHIEP, LOAIMON) VALUES ('7480201_DKD', 'PHY00005', 2, 1, 'Bắt buộc');

-- 13. Thêm dữ liệu bảng LOPHOCPHAN
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP001', 'CSC00004', '24C07', 'Tiết Gia Hồng', 'tghong@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP002', 'CSC10012', '24C07', 'Nguyễn Hải Minh', 'nhminh@hcmus.edu.vn', 'tiếng Anh', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP003', 'CSC10121', '24C07', 'Lê Thu Thảo', 'ltthao@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP004', 'MTH00009', '24C05', 'Lê Văn Luyện', 'lvluyen@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP005', 'BAA00004', '24C04', 'Đặng Công Tráng', 'dctrang@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP006', 'CSC10004', '24C07', 'Nguyễn Ngọc Thảo', 'nnthao@hcmus.edu.vn', 'tiếng Anh', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP007', 'MTH00058', '24C05', 'Nguyễn Hữu Trí Nhật', 'nhtnhat@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP008', 'PHY00005', '24C05', 'Huỳnh Trúc Phương', 'htphuong@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP009', 'CSC10003', '24C07', 'Trần Duy Quang', 'tdquang@hcmus.edu.vn', 'tiếng Anh', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP010', 'CSC10008', '24C07', 'Lê Hà Minh', 'lhminh@hcmus.edu.vn', 'tiếng Việt', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP011', 'MTH00005', '24C05', 'Nguyễn Vũ Huy', 'nvhuy@hcmus.edu.vn', 'tiếng Việt', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP012', 'MTH00008', '24C05', 'Nguyễn Hữu Trí Nhật', 'nhtnhat@hcmus.edu.vn', 'tiếng Việt', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP013', 'BAA00005', '24C05', 'Nguyễn Thị Đông', 'ntdong@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP014', 'BAA00030', '24CTT_DKD', NULL, NULL, 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP015', 'CSC10009', '24C07', 'Nguyễn Hồng Bửu Long', 'nhblong@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP016', 'CSC10014', '24C07', 'Lê Khánh Duy', 'lkduy@hcmus.edu.vn', 'tiếng Anh', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP017', 'MTH00006', '24C05', 'Nguyễn Vũ Huy', 'nvhuy@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP018', 'BAA00021', '24C07', 'Lê Hải', 'lhai@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP019', 'BAA00101', '24C04', 'Nguyễn Thanh Hải', 'nthai@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP020', 'CSC10007', '24C07', 'Lê Viết Long', 'lvlong@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP021', 'MTH00007', '24C05', 'Nguyễn Đăng Minh', 'ndminh@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP022', 'BAA00022 ', '24C07', 'Đỗ Thành Quang', 'dtquang@hcmus.edu.vn', 'tiếng Việt', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP023', 'BAA00102', '24C04', 'Mạch Thị Khánh Trinh', 'mtktrinh@hcmus.edu.vn', 'tiếng Việt', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP024', 'CSC10006', '24C07', 'Vũ Thị Mỹ Hằng', 'vtmhang@hcmus.edu.vn', 'tiếng Anh', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP025', 'CSC13002', '24C07', 'Nguyễn Văn Vũ', 'nvvu@hcmus.edu.vn', 'tiếng Anh', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP026', 'MTH00057', '24C04', 'Vũ Quốc Hoàng', 'vqhoang@hcmus.edu.vn', 'tiếng Việt', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP027', 'ADD00031', '24CTT1', 'Nguyễn Thị A', 'nta@hcmus.edu.vn', 'tiếng Anh', 'HK001', 'CLosed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP028', 'BAA00021', '24CL_T4Ti8', 'Nguyễn Thị B', 'ntb@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP029', 'BAA00101', '24TTH3', 'Nguyễn Thị C', 'ntc@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP030', 'CSC00003', 'C6B', 'Nguyễn Thị D', 'ntd@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP031', 'MTH00010', '24TTH3', 'Nguyễn Thị E', 'nte@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP032', 'MTH00011', '24TTH3', 'Nguyễn Thị F', 'ntf@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP033', 'MTH00034', '24TTH3', 'Nguyễn Thị G', 'ntg@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP034', 'MTH00043', '24TTH3', 'Nguyễn Thị H', 'nth@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP035', 'MTH00088', '24TTH3A', 'Nguyễn Thị I', 'nti@hcmus.edu.vn', 'tiếng Việt', 'HK001', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP036', 'BAA00004', '24TTH3', 'Nguyễn Thị J', 'ntj@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP037', 'BAA00005', '24_2', 'Nguyễn Thị K', 'ntk@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP038', 'BAA00022', '24CL_T4Ti3', 'Nguyễn Thị L', 'ntl@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP039', 'MTH00013', '24TTH3', 'Nguyễn Thị M', 'ntm@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP040', 'MTH00017', '24TTH3', 'Nguyễn Thị N', 'ntn@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP041', 'MTH00055', '24TTH1', 'Nguyễn Thị O', 'nto@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP042', 'MTH10441', '24TTH3', 'Nguyễn Thị P', 'ntp@hcmus.edu.vn', 'tiếng Việt', 'HK002', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP043', 'GEO00002', '24_HE1', 'Nguyễn Thị Q', 'ntq@hcmus.edu.vn', 'tiếng Việt', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP044', 'PHY00001', '24_HE1', 'Nguyễn Thị R', 'ntr@hcmus.edu.vn', 'tiếng Việt', 'HK003', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP045', 'BAA00102', '24TTH1', 'Nguyễn Thị S', 'nts@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP046', 'MTH10405', '24KDL1', 'Nguyễn Thị T', 'ntt@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP047', 'ADD00032', '24S3_1', 'Nguyễn Thị U', 'ntu@hcmus.edu.vn', 'tiếng Anh', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP048', 'MTH00031', '24TTH1', 'Nguyễn Thị V', 'ntv@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP049', 'MTH00042', '24TTH1', 'Nguễn Thị W', 'ntw@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP050', 'BAA00003', '24CMT1', 'Nguyễn Thị Y', 'nty@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP051', 'PHY00002', '24KDL1', 'Nguyễn Thị Z', 'ntz@hcmus.edu.vn', 'tiếng Việt', 'HK004', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP052', 'MTH00017', '25TTH2', 'Trần Văn A', 'tva@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP053', 'MTH10109', '24TTH2', 'Trần Văn B', 'tvb@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP054', 'MTH10131', '24TTH1', 'Trần Văn C', 'tvc@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP055', 'MTH10312', '24TTH2', 'Trần Văn D', 'tv@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP056', 'MTH10407', '24TTH2', 'Trần Văn E', 'tve@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP057', 'MTH10442', '24TTH1', 'Trần Văn F', 'tvf@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP058', 'MTH10449', '24TTH_KDL1', 'Trần Văn G', 'tvg@hcmus.edu.vn', 'tiếng Việt', 'HK005', 'Closed');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP059', 'BAA00103', '25_HE3', 'Trần Văn H', 'tvh@hcmus.edu.vn', 'tiếng Việt', 'HK006', 'Open');
INSERT INTO LOPHOCPHAN (MALHP, MAMH, TENLOP, TENGV, MAILGV, NGONNGU, MA_HOCKY, TRANGTHAI) VALUES ('HP060', 'BAA00104', '25_HE2', 'Trần Văn I', 'tvi@hcmus.edu.vn', 'tiếng Việt', 'HK006', 'Open');

-- 14. Thêm dữ liệu bảng LICH_HOC
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH001', 'HP001', 1, '2024-09-16', '2024-09-21', 'Hai', '07:30:00', '11:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH002', 'HP001', 2, '2024-09-23', '2024-09-28', 'Hai', '07:30:00', '11:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH003', 'HP001', 3, '2024-09-30', '2024-10-05', 'Hai', '07:30:00', '11:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH004', 'HP001', 4, '2024-10-07', '2024-10-12', 'Hai', '07:30:00', '11:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH005', 'HP001', 5, '2024-10-14', '2024-10-19', 'Hai', '07:30:00', '11:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH006', 'HP002', 1, '2024-09-16', '2024-09-21', 'Ba', '07:30:00', '11:10:00', 'I.23', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH007', 'HP003', 1, '2021-09-16', '2024-09-21', 'Ba', '13:30:00', '17:10:00', 'I.44', 'Trực tiếp');
INSERT INTO LICH_HOC (MALICHHOC, MALHP, TUAN, NGAYBATDAU, NGAYKETTHUC, THU, THOIGIAN_BD, THOIGIAN_KT, PHONGHOC, HINHTHUCHOC) VALUES ('LH008', 'HP004', 1, '2021-09-16', '2024-09-21', 'Sáu', '07:30:00', '11:10:00', 'C.22', 'Trực tiếp');

-- 15. Thêm dữ liệu bảng LICH_THI
INSERT INTO LICH_THI (MALICHTHI, MALHP, NGAYTHI, GIOTHI, THOIGIANLAMBAI, PHONGTHI) VALUES ('LT001', 'HP001', '2024-12-25', '13:30:00', 60, 'B.40');
INSERT INTO LICH_THI (MALICHTHI, MALHP, NGAYTHI, GIOTHI, THOIGIANLAMBAI, PHONGTHI) VALUES ('LT002', 'HP002', '2024-12-23', '13:30:00', 90, 'E.301');
INSERT INTO LICH_THI (MALICHTHI, MALHP, NGAYTHI, GIOTHI, THOIGIANLAMBAI, PHONGTHI) VALUES ('LT003', 'HP004', '2024-12-27', '13:30:00', 90, 'I.32');

-- 16. Thêm dữ liệu bảng KETQUA_HOCTAP
INSERT INTO KETQUA_HOCTAP (MSSV, MALHP, DIEMGK, DIEMCK, DIEMTB_HE10, LOAIDIEM_HECHU, TRANGTHAI) VALUES ('24127158', 'HP001', 8, 8.8, 8.6, 'A', 'Closed');
INSERT INTO KETQUA_HOCTAP (MSSV, MALHP, DIEMGK, DIEMCK, DIEMTB_HE10, LOAIDIEM_HECHU, TRANGTHAI) VALUES ('24127158', 'HP002', 8, 5, 7.2, 'A', 'Closed');
INSERT INTO KETQUA_HOCTAP (MSSV, MALHP, DIEMGK, DIEMCK, DIEMTB_HE10, LOAIDIEM_HECHU, TRANGTHAI) VALUES ('24127158', 'HP003', NULL, 9.9, 9.3, 'A+', 'Closed');
INSERT INTO KETQUA_HOCTAP (MSSV, MALHP, DIEMGK, DIEMCK, DIEMTB_HE10, LOAIDIEM_HECHU, TRANGTHAI) VALUES ('24127158', 'HP004', 5, 8, 7.6, 'B', 'Closed');

-- 17. Thêm dữ liệu bảng HOCPHHI
INSERT INTO HOCPHI (MSSV, MALHP, SOTCHP, HOCPHI_GOC, MUCGIAM, HOTRO, THUCDONG, CHIPHIKHAC, GHICHU, TRANGTHAI_THANHTOAN, NGAYTHANHTOAN) VALUES ('24127158', 'HP001', 6, 6000000.00, 0.00, 0.00, 6000000.00, 0.00, NULL, 1, '2024-02-13T00:00:00.000');
INSERT INTO HOCPHI (MSSV, MALHP, SOTCHP, HOCPHI_GOC, MUCGIAM, HOTRO, THUCDONG, CHIPHIKHAC, GHICHU, TRANGTHAI_THANHTOAN, NGAYTHANHTOAN) VALUES ('24127158', 'HP002', 7, 7000000.00, 0.00, 0.00, 7000000.00, 0.00, NULL, 1, '2024-02-13T00:00:00.000');
INSERT INTO HOCPHI (MSSV, MALHP, SOTCHP, HOCPHI_GOC, MUCGIAM, HOTRO, THUCDONG, CHIPHIKHAC, GHICHU, TRANGTHAI_THANHTOAN, NGAYTHANHTOAN) VALUES ('24127158', 'HP003', 5, 5000000.00, 0.00, 0.00, 5000000.00, 0.00, NULL, 1, '2024-02-13T00:00:00.000');
INSERT INTO HOCPHI (MSSV, MALHP, SOTCHP, HOCPHI_GOC, MUCGIAM, HOTRO, THUCDONG, CHIPHIKHAC, GHICHU, TRANGTHAI_THANHTOAN, NGAYTHANHTOAN) VALUES ('24127158', 'HP004', 5, 5000000.00, 0.00, 0.00, 50000000.00, 0.00, NULL, 1, '2024-02-13T00:00:00.000');

-- 16. Thêm dữ liệu bảng NGUOITHAN
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010011', '24001001', 'Nguyễn Hữu B', 1978, 'Cha', 'Thợ mộc', 'Quận 1, TP.HCM', '0911234501', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 1', 'Quận 1, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010021', '24001002', 'Trần Văn C', 1980, 'Cha', 'Bác sĩ', 'Quận 3, TP.HCM', '0911234502', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 3', 'Quận 3, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010031', '24001003', 'Lê Thị D', 1981, 'Mẹ', 'Y tá', 'Quận 5, TP.HCM', '0911234503', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 5', 'Quận 5, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010041', '24001004', 'Phạm Văn E', 1977, 'Cha', 'Giáo viên', 'Quận 7, TP.HCM', '0911234504', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 7', 'Quận 7, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010051', '24001005', 'Hoàng Thị F', 1970, 'Mẹ', 'Ca sĩ', 'Quận 10, TP.HCM', '0911234505', NULL, 'Kinh', 'Thiên Chúa Giáo', 'Việt Nam', 'TP.HCM', 'Quận 10', 'Quận 10, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010061', '24001006', 'Đặng Văn G', 1980, 'Cha', 'Thợ cắt tóc', 'Gò Vấp. TP.HCM', '0911234506', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Gò Vấp', 'Gò Vấp. TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010071', '24001007', 'Vũ Thị H', 1976, 'Mẹ', 'Điều dưỡng', 'Tân Bình, TP.HCM', '0911234507', NULL, 'Kinh', 'Phật Giáo', 'Việt Nam', 'TP.HCM', 'Tân Bình', 'Tân Bình, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010081', '24001008', 'Vũ Văn I', 1975, 'Cha', 'Đầu bếp', 'Bình Tân, TP.HCM', '0911234508', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Bình Tân', 'Bình Tân, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010091', '24001009', 'Phan Thị K', 1978, 'Mẹ', 'Kinh doanh', 'Phú Nhuận, TP.HCM', '0911234509', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Phú Nhuận', 'Phú Nhuận, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010101', '24001010', 'Trương Văn L', 1990, 'Cha', 'Kinh doanh', 'Bình Thạnh, TP.HCM', '0911234510', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Bình Thạnh', 'Bình Thạnh, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010111', '24001011', 'Bùi Thị M', 1989, 'Mẹ', 'Giáo viên', 'Tân Phú, TP.HCM', '0911234511', NULL, 'Kinh', 'Cao Đài', 'Việt Nam', 'TP.HCM', 'Tân Phú', 'Tân Phú, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010121', '24001012', 'Đỗ Văn N', 1990, 'Cha', 'Diễn viên', 'Quận 12, TP.HCM', '0911234512', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 12', 'Quận 12, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010131', '24001013', 'Hồ Thị O', 1979, 'Mẹ', 'Kinh doanh', 'Thủ Đức, TP.HCM', '0911234513', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Thủ Đức', 'Thủ Đức, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010141', '24001014', 'Ngô Văn P', 1980, 'Cha', 'Làm nông', 'Quận 4, TP.HCM', '0911234514', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 4', 'Quận 4, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010151', '24001015', 'Dương Thị Q', 1987, 'Mẹ', 'Kinh doanh', 'Quận 6, TP.HCM', '0911234515', NULL, 'Kinh', 'Phật giáo', 'Việt Nam', 'TP.HCM', 'Quận 6', 'Quận 6, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010161', '24001016', 'Lý Văn R', 1970, 'Cha', 'Giáo viên', 'Quận 8, TP.HCM', '0911234516', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 8', 'Quận 8, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010171', '24001017', 'Phạm Thị S', 1980, 'Mẹ', 'Kinh doanh', 'Quận 11, TP.HCM', '0911234517', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 11', 'Quận 11, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010181', '24001018', 'Trần Văn T', 1975, 'Cha', 'Nông dân', 'Hóc Môn, TP.HCM', '0911234518', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Hóc Môn', 'Hóc Môn, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240010191', '24001019', 'Nguyễn Thị V', 1981, 'Mẹ', 'Kinh doanh', 'Củ Chi, TP.HCM', '0911234519', NULL, 'Kinh', 'Thiên Chúa Giáo', 'Việt Nam', 'TP.HCM', 'Củ Chi', 'Củ Chi, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020011', '24002001', 'Lê Văn B', 1967, 'Cha', 'Kinh doanh', 'Quận 7, TP.HCM', '0911234520', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 7', 'Quận 7, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020021', '24002002', 'Trần Văn C', 1985, 'Cha', 'Bác sĩ', 'Gò Vấp, TP.HCM', '0911234521', NULL, 'Kinh', 'Cao Đài', 'Việt Nam', 'TP.HCM', 'Gò Vấp', 'Gò Vấp, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020031', '24002003', 'Phạm Thị D', 1984, 'Mẹ', 'Kinh doanh', 'Thủ Đức, TP.HCM', '0911234522', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Thủ Đức', 'Thủ Đức, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020041', '24002004', 'Nguyễn Văn E', 1986, 'Cha', 'Giáo viên', 'Quận 7, TP.HCM', '0911234523', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 7', 'Quận 7, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020051', '24002005', 'Đinh Thị F', 1980, 'Mẹ', 'Kinh doanh', 'Quận 10, TP.HCM', '0911234524', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Quận 10', 'Quận 10, TP.HCM');
INSERT INTO NGUOITHAN (MANT, MSSV, HOTEN, NAMSINH, QUANHE, NGHENGHIEP, NOILAMVIEC, SDT, MAIL, DANTOC, TONGIAO, QUOCTICH, TINHTHANH, PHUONGXA, HKTHUONGTRU) VALUES ('240020061', '24002006', 'Vũ Văn G', 1969, 'Cha', 'Thợ cắt tóc', 'Tân Bình, TP.HCM', '0911234525', NULL, 'Kinh', 'Không', 'Việt Nam', 'TP.HCM', 'Tân Bình', 'Tân Bình, TP.HCM');